## OCCUPANCY
message_occupancy:
  mode: 'queued'
  sequence:
  - service: notify.telegram_home_group_id
    data_template:
      message: | 
        â±ï¸ ĞŸÑ€Ğ¸ÑÑƒÑ‚ÑÑ‚Ğ²Ğ¸Ğµ ......... {{ state_attr('sensor.date_time', 'hm') }} UTC
        ğŸ¥£ ĞšÑƒÑ…Ğ½Ñ ..................... {{ iif(is_state('binary_sensor.motion_kitchen_boolean', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
        ğŸ› Ğ’Ğ°Ğ½Ğ½Ğ°Ñ ................... {{ iif(is_state('binary_sensor.motion_bath_boolean', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
        ğŸš½ Ğ¢ÑƒĞ°Ğ»ĞµÑ‚ ................... {{ iif(is_state('binary_sensor.occupancy_toilet_boolean', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
        ğŸ§¥ ĞšĞ¾Ñ€Ğ¸Ğ´Ğ¾Ñ€ ................ {{ iif(is_state('binary_sensor.motion_hall_boolean', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
      data:
        inline_keyboard: 
        - 'ĞĞ°Ğ·Ğ°Ğ´:/security, ĞĞ±Ğ½Ğ¾Ğ²Ğ¸Ñ‚ÑŒ:/security_occupancy, Ğ—Ğ°ĞºÑ€Ñ‹Ñ‚ÑŒ:/hide_menu'

## WINDOW
message_window:
  mode: 'queued'
  sequence:
  - service: notify.telegram_home_group_id
    data_template:
      message: | 
        â±ï¸ ĞĞºĞ½Ğ° ....................... {{ state_attr('sensor.date_time', 'hm') }} UTC
        ğŸ¥£ ĞšÑƒÑ…Ğ½Ñ Ğ»ĞµĞ²Ğ¾Ğµ ........... {{ iif(is_state('binary_sensor.window_kitchen_left_open', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
        ğŸ¥£ ĞšÑƒÑ…Ğ½Ñ Ğ¿Ñ€Ğ°Ğ²Ğ¾Ğµ ......... {{ iif(is_state('binary_sensor.window_kitchen_right_open', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
        ğŸ›Œ Ğ¡Ğ¿Ğ°Ğ»ÑŒĞ½Ñ Ğ»ĞµĞ²Ğ¾Ğµ ....... {{ iif(is_state('binary_sensor.window_bedroom_left_open', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
        ğŸ›Œ Ğ¡Ğ¿Ğ°Ğ»ÑŒĞ½Ñ Ğ¿Ñ€Ğ°Ğ²Ğ¾Ğµ ..... {{ iif(is_state('binary_sensor.window_bedroom_right_open', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
        ğŸ“š Ğ“Ğ¾ÑÑ‚Ğ¸Ğ½Ğ°Ñ ................. {{ iif(is_state('binary_sensor.window_living_open', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
      data:
        inline_keyboard: 
        - 'ĞĞ°Ğ·Ğ°Ğ´:/security, ĞĞ±Ğ½Ğ¾Ğ²Ğ¸Ñ‚ÑŒ:/security_window, Ğ—Ğ°ĞºÑ€Ñ‹Ñ‚ÑŒ:/hide_menu'

## DOOR
message_door:
  mode: 'queued'
  sequence:
  - service: notify.telegram_home_group_id
    data_template:
      message: | 
        â±ï¸ Ğ”Ğ²ĞµÑ€Ğ¸ ................... {{ state_attr('sensor.date_time', 'hm') }} UTC
        ğŸš½ Ğ¢ÑƒĞ°Ğ»ĞµÑ‚ ................... {{ iif(is_state('binary_sensor.door_toilet_open', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
        ğŸ§¥ ĞšĞ¾Ñ€Ğ¸Ğ´Ğ¾Ñ€ ................ {{ iif(is_state('binary_sensor.door_hall_open', 'on'), 'ğŸŸ¢', 'ğŸ”´') }}
        ğŸ›Œ Ğ¡Ğ¿Ğ°Ğ»ÑŒĞ½Ñ ................. {{ iif(is_state('binary_sensor.door_bedroom_open', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
        ğŸ“š Ğ“Ğ¾ÑÑ‚Ğ¸Ğ½Ğ°Ñ ................ {{ iif(is_state('binary_sensor.door_living_open', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
        ğŸª´ Ğ‘Ğ°Ğ»ĞºĞ¾Ğ½ ................... {{ iif(is_state('binary_sensor.door_balcony_open', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
      data:
        inline_keyboard: 
        - 'ĞĞ°Ğ·Ğ°Ğ´:/security, ĞĞ±Ğ½Ğ¾Ğ²Ğ¸Ñ‚ÑŒ:/security_door, Ğ—Ğ°ĞºÑ€Ñ‹Ñ‚ÑŒ:/hide_menu'

message_door_hall:
  mode: 'queued'
  sequence:
  - service: notify.telegram_home_group_id
    data_template:
      message: | 
        â±ï¸ Ğ”Ğ²ĞµÑ€ÑŒ ................... {{ state_attr('sensor.date_time', 'hm') }} UTC
        ğŸ§¥ ĞšĞ¾Ñ€Ğ¸Ğ´Ğ¾Ñ€ ................ {{ iif(is_state('binary_sensor.door_hall_open', 'on'), 'ğŸŸ¢', 'ğŸ”´') }}
      data:
        inline_keyboard: 
        - 'ĞœĞµĞ½Ñ:/home, Ğ—Ğ°ĞºÑ€Ñ‹Ñ‚ÑŒ:/hide_menu'

message_door_balcony:
  mode: 'queued'
  sequence:
  - service: notify.telegram_home_group_id
    data_template:
      message: | 
        â±ï¸ Ğ”Ğ²ĞµÑ€ÑŒ ................... {{ state_attr('sensor.date_time', 'hm') }} UTC
        ğŸª´ Ğ‘Ğ°Ğ»ĞºĞ¾Ğ½ ................... {{ iif(is_state('binary_sensor.door_balcony_open', 'on'), 'ğŸŸ¢', 'ğŸŸ ') }}
      data:
        inline_keyboard: 
        - 'ĞœĞµĞ½Ñ:/home, Ğ—Ğ°ĞºÑ€Ñ‹Ñ‚ÑŒ:/hide_menu'
